### ISSUE TITLE
Syntax highlight conflict with package language-php

### ISSUE THREAD

**Issue by cakebake** [jawee/atom-typo3#3]
Hey,

first of all - many thank´s for your package, it is very useful!

I have a conflict found with package language-php. It takes place when both are active.

**Comment by mneuhaus** [comment]
some issue here, i think the issue is, that you declared the fluid syntax to apply to php files, which is kind of odd to be honest. because of that atom uses the fluid syntax to highlight php files :(

**Comment by chvonrohr** [comment]
:+1:  *.php should not have syntax "Fluid"

**Comment by MrTuTu** [comment]
Hi,
Thank you for your package !!
Could you remove the support for "php" extension ?
Thank you

**Comment by cakebake** [comment]
I think he added it because of some php snippets.

https://github.com/jawee/atom-typo3/blob/master/snippets/typo3.cson#L67

@jawee I think the package could be splitted to different packages. If you discontinued development for this package, please let me know and I will fork it.

**Comment by jawee** [comment]
@cakebake I haven't really spent any time on it for a while since I'm not working with typo3 anymore, but I'm more than willing to take care of pull requests. :)

**Comment by cakebake** [comment]
I think that's even better! I'll remove the PHP part of the package.
